name: Fetch Dog Image

on:
  schedule:
    - cron: '50,55 * * * *'   # 每天凌晨 1 点（UTC）自动执行
  workflow_dispatch:      # 允许手动运行

jobs:
  fetch-dog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch dog image URL
        run: |
          curl https://dog.ceo/api/breeds/image/random > data.json

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.json
          git commit -m "update dog image"
          git push
