name: Fetch Dog Image

on:
  schedule:
    - cron: '0,57 * * * *'   # 每天凌晨 1 点（UTC）自动执行
  workflow_dispatch:      # 允许手动运行

permissions:
  contents: write            # ✅ 允许对仓库内容有写权限
jobs:
  fetch-dog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch dog image URL
        run: |
          curl https://dog.ceo/api/breeds/image/random > data.json

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "update dog image"
          git push
